### PR TITLE
Limit the number of inflight requests

### LINKED ISSUE #83: ketall with EKS and aws-iam-authenticator leads to socket exhaustion
**Describe the bug**
Using ketall with an EKS setup and https://github.com/kubernetes-sigs/aws-iam-authenticator leads to many aws client created and eventually socket descriptor exhaustion.

**To Reproduce**
1. Have an EKS + IAM auth setup
2. Run kubectl get-all
3. You'll see a bunch of messages like (with the client count incrementing): 
```W0828 08:26:24.925622   16543 exec.go:201] constructing many client instances from the same exec auth config can cause performance problems during cert rotation and can exhaust available network connections; 1831 clients constructed calling "aws"```
4. Then error messages like : 
```WARN[0035] Cannot fetch: Get https://REDACTED.gr7.us-east-1.eks.amazonaws.com/apis/extensions/v1beta1/replicasets: dial tcp 10.6.4.45:443: socket: too many open files```

**Expected behavior**
The plugin should reuse the aws instance? Not so sure where the problem lies TBH, feel free to redirect me!

**Desktop (please complete the following information):**
 - get-all  v1.3.2
 - OS: Ubuntu 18.04

**Additional context**
Related issue : https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/308
Might help others too if I link https://github.com/kubernetes/kubectl/issues/151 (that's how I ended up finding your plugin)

### PR DESCRIPTION
**Pull request by corneliusweig**
Fix #83

### CODE REVIEW

**Comment by corneliusweig** [comment]
@jebeaudet can you help out to verify if this fixes the problem? For that you need to build this branch and check out if you still experience this issue #83 . The easiest way to build a binary for your arch is `make dev` in the cloned repository.

I limited the number of inflight requests to 64. If this is still too much, please try to find a concurrency that still works for you via the `--max-inflight` parameter. You could also try to make this bigger, because I'd like to have this as large as possible. `Ketall` already is a bit sluggish and limiting the inflight requests makes it even worse.

**Comment by jebeaudet** [comment]
Sure thing! I'll test it out tomorrow and lot you know. Thanks!

**Comment by jebeaudet** [comment]
Works like a charm, I don't get the warnings anymore and everything works as it should.

I've tested it on my fairly large EKS setup with some `max-inflight` values and here are the results (in terms of concurrency, higher is not always better!) : 
```
--max-inflight=12
real	0m47.966s
user	1m39.120s
sys	0m13.766s

--max-inflight=32
real	0m41.704s
user	2m1.693s
sys	0m17.293s

--max-inflight=64
real	0m39.143s
user	2m1.190s
sys	0m16.395s

--max-inflight=128
real	0m43.899s
user	2m5.514s
sys	0m18.934s

--max-inflight=256
real	0m41.598s
user	1m55.171s
sys	0m16.327s

--max-inflight=512
real	0m43.184s
user	2m10.304s
sys	0m21.093s
```

64 looks like a sweet spot for me though the differences are probably negligeable in the end. 

Thanks again, let me know if I can be of further help :tada:

**Comment by corneliusweig** [comment]
Thank you for providing these numbers. I think 64 parallel requests is quite ok, so let's make that the default.

**Pull request merged**
